.TH TRELLO "1" "March 2019" "trello 0.2.1" "Trello CLI"
.SH NAME
trello \- A trello command-line client tool
.SH SYNOPSIS
Usage: trello [command]
.SH DESCRIPTION
trello-cli is a free and open-source client for Trello built in NodeJS.
The source code for the project is available on GitHub at https://github.com/mheap/trello-cli
.SH COMMANDS
.TP
set\-auth
Sets developer API key into configuration file
.TP
add\-board
Adds a new board with the specified name
.TP
add\-card
Add a card to a board
.TP
add\-list
Adds a new list to the spcified board with the specified name
.TP
add\-webhook
Add a webhook to a board
.TP
archive\-card
Archive a card from a board
.TP
assigned\-to\-me
Show cards that are currently assigned to yourself, or any member specified
.TP
card\-assign
Add or remove a member to a card
.TP
card\-details
Show details about a specified card
.TP
close\-board
Closes those board(s) where the specified text occurs in their name
.TP
delete\-card
Remove a card from a board
.TP
delete\-webhook
Remove a webhook by ID
.TP
move\-all\-cards
Move all cards from one list to another
.TP
move\-card
Move a card on a board
.TP
refresh
Refresh all your board/list names
.TP
show\-boards
Show the list of cached boards
.TP
show\-cards
Show the cards on a list
.TP
show\-labels
Show labels defined on a board
.TP
show\-lists
Show the list of cached lists
.TP
show\-webhooks
Display webhooks for current user applications
.SH AUTHOR
trello-cli was created by Michael Heap <m@michaelheap.com>
.SH LICENSE
trello-cli is licensed under BSD
.SH REQUIREMENTS
A developer API key is required for trello-cli. Get yours by first login in to Trello then by visiting https://trello.com/app-key.
Once you acquired your developer API key, use the 'set-auth' option to add it to the configuration file
